// Generated by gencpp from file sigma_ros/haptic_commands.msg
// DO NOT EDIT!


#ifndef SIGMA_ROS_MESSAGE_HAPTIC_COMMANDS_H
#define SIGMA_ROS_MESSAGE_HAPTIC_COMMANDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sigma_ros
{
template <class ContainerAllocator>
struct haptic_commands_
{
  typedef haptic_commands_<ContainerAllocator> Type;

  haptic_commands_()
    : lock_position(false)
    , lock_orientation(false)
    , lock_grasp(false)  {
    }
  haptic_commands_(const ContainerAllocator& _alloc)
    : lock_position(false)
    , lock_orientation(false)
    , lock_grasp(false)  {
  (void)_alloc;
    }



   typedef uint8_t _lock_position_type;
  _lock_position_type lock_position;

   typedef uint8_t _lock_orientation_type;
  _lock_orientation_type lock_orientation;

   typedef uint8_t _lock_grasp_type;
  _lock_grasp_type lock_grasp;





  typedef boost::shared_ptr< ::sigma_ros::haptic_commands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sigma_ros::haptic_commands_<ContainerAllocator> const> ConstPtr;

}; // struct haptic_commands_

typedef ::sigma_ros::haptic_commands_<std::allocator<void> > haptic_commands;

typedef boost::shared_ptr< ::sigma_ros::haptic_commands > haptic_commandsPtr;
typedef boost::shared_ptr< ::sigma_ros::haptic_commands const> haptic_commandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sigma_ros::haptic_commands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sigma_ros::haptic_commands_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sigma_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sigma_ros': ['/home/raven/bgu_raven_comp/src/sigma_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sigma_ros::haptic_commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sigma_ros::haptic_commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sigma_ros::haptic_commands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sigma_ros::haptic_commands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sigma_ros::haptic_commands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sigma_ros::haptic_commands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sigma_ros::haptic_commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3d68c3bf92fad21eb2fbd9a92b56e17";
  }

  static const char* value(const ::sigma_ros::haptic_commands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3d68c3bf92fad21ULL;
  static const uint64_t static_value2 = 0xeb2fbd9a92b56e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::sigma_ros::haptic_commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sigma_ros/haptic_commands";
  }

  static const char* value(const ::sigma_ros::haptic_commands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sigma_ros::haptic_commands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool lock_position\n\
bool lock_orientation\n\
bool lock_grasp\n\
";
  }

  static const char* value(const ::sigma_ros::haptic_commands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sigma_ros::haptic_commands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lock_position);
      stream.next(m.lock_orientation);
      stream.next(m.lock_grasp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct haptic_commands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sigma_ros::haptic_commands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sigma_ros::haptic_commands_<ContainerAllocator>& v)
  {
    s << indent << "lock_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lock_position);
    s << indent << "lock_orientation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lock_orientation);
    s << indent << "lock_grasp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lock_grasp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGMA_ROS_MESSAGE_HAPTIC_COMMANDS_H
