# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bgusigma/amit_raven/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bgusigma/amit_raven/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/bgusigma/amit_raven/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/bgusigma/amit_raven/src/CMakeFiles /home/bgusigma/amit_raven/src/sigma_ros/CMakeFiles/progress.marks
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bgusigma/amit_raven/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/bgusigma/amit_raven/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_genpy.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_genpy.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_genpy.dir/rule

# Convenience name for target.
sigma_ros_genpy: sigma_ros/CMakeFiles/sigma_ros_genpy.dir/rule

.PHONY : sigma_ros_genpy

# fast build rule for target.
sigma_ros_genpy/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_genpy.dir/build.make sigma_ros/CMakeFiles/sigma_ros_genpy.dir/build
.PHONY : sigma_ros_genpy/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/rule

# Convenience name for target.
sigma_ros_gennodejs: sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/rule

.PHONY : sigma_ros_gennodejs

# fast build rule for target.
sigma_ros_gennodejs/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/build.make sigma_ros/CMakeFiles/sigma_ros_gennodejs.dir/build
.PHONY : sigma_ros_gennodejs/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/rule

# Convenience name for target.
sigma_ros_generate_messages_cpp: sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/rule

.PHONY : sigma_ros_generate_messages_cpp

# fast build rule for target.
sigma_ros_generate_messages_cpp/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages_cpp.dir/build
.PHONY : sigma_ros_generate_messages_cpp/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_geneus.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_geneus.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_geneus.dir/rule

# Convenience name for target.
sigma_ros_geneus: sigma_ros/CMakeFiles/sigma_ros_geneus.dir/rule

.PHONY : sigma_ros_geneus

# fast build rule for target.
sigma_ros_geneus/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_geneus.dir/build.make sigma_ros/CMakeFiles/sigma_ros_geneus.dir/build
.PHONY : sigma_ros_geneus/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/rule

# Convenience name for target.
sigma_ros_generate_messages_py: sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/rule

.PHONY : sigma_ros_generate_messages_py

# fast build rule for target.
sigma_ros_generate_messages_py/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages_py.dir/build
.PHONY : sigma_ros_generate_messages_py/fast

# Convenience name for target.
sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/rule
.PHONY : sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/rule

# Convenience name for target.
_sigma_ros_generate_messages_check_deps_haptic_commands: sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/rule

.PHONY : _sigma_ros_generate_messages_check_deps_haptic_commands

# fast build rule for target.
_sigma_ros_generate_messages_check_deps_haptic_commands/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/build.make sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_commands.dir/build
.PHONY : _sigma_ros_generate_messages_check_deps_haptic_commands/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/rule

# Convenience name for target.
sigma_ros_generate_messages_eus: sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/rule

.PHONY : sigma_ros_generate_messages_eus

# fast build rule for target.
sigma_ros_generate_messages_eus/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages_eus.dir/build
.PHONY : sigma_ros_generate_messages_eus/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/rule

# Convenience name for target.
sigma_ros_generate_messages: sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/rule

.PHONY : sigma_ros_generate_messages

# fast build rule for target.
sigma_ros_generate_messages/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages.dir/build
.PHONY : sigma_ros_generate_messages/fast

# Convenience name for target.
sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/rule
.PHONY : sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/rule

# Convenience name for target.
_sigma_ros_generate_messages_check_deps_haptic_device: sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/rule

.PHONY : _sigma_ros_generate_messages_check_deps_haptic_device

# fast build rule for target.
_sigma_ros_generate_messages_check_deps_haptic_device/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/build.make sigma_ros/CMakeFiles/_sigma_ros_generate_messages_check_deps_haptic_device.dir/build
.PHONY : _sigma_ros_generate_messages_check_deps_haptic_device/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/rule

# Convenience name for target.
sigma_ros_generate_messages_nodejs: sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/rule

.PHONY : sigma_ros_generate_messages_nodejs

# fast build rule for target.
sigma_ros_generate_messages_nodejs/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages_nodejs.dir/build
.PHONY : sigma_ros_generate_messages_nodejs/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/rule

# Convenience name for target.
sigma_ros_gencpp: sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/rule

.PHONY : sigma_ros_gencpp

# fast build rule for target.
sigma_ros_gencpp/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/build.make sigma_ros/CMakeFiles/sigma_ros_gencpp.dir/build
.PHONY : sigma_ros_gencpp/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_node.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_node.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_node.dir/rule

# Convenience name for target.
sigma_ros_node: sigma_ros/CMakeFiles/sigma_ros_node.dir/rule

.PHONY : sigma_ros_node

# fast build rule for target.
sigma_ros_node/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/build
.PHONY : sigma_ros_node/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/rule

# Convenience name for target.
sigma_ros_generate_messages_lisp: sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/rule

.PHONY : sigma_ros_generate_messages_lisp

# fast build rule for target.
sigma_ros_generate_messages_lisp/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/build.make sigma_ros/CMakeFiles/sigma_ros_generate_messages_lisp.dir/build
.PHONY : sigma_ros_generate_messages_lisp/fast

# Convenience name for target.
sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/rule:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f CMakeFiles/Makefile2 sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/rule
.PHONY : sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/rule

# Convenience name for target.
sigma_ros_genlisp: sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/rule

.PHONY : sigma_ros_genlisp

# fast build rule for target.
sigma_ros_genlisp/fast:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/build.make sigma_ros/CMakeFiles/sigma_ros_genlisp.dir/build
.PHONY : sigma_ros_genlisp/fast

src/Sigma.o: src/Sigma.cpp.o

.PHONY : src/Sigma.o

# target to build an object file
src/Sigma.cpp.o:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/Sigma.cpp.o
.PHONY : src/Sigma.cpp.o

src/Sigma.i: src/Sigma.cpp.i

.PHONY : src/Sigma.i

# target to preprocess a source file
src/Sigma.cpp.i:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/Sigma.cpp.i
.PHONY : src/Sigma.cpp.i

src/Sigma.s: src/Sigma.cpp.s

.PHONY : src/Sigma.s

# target to generate assembly for a file
src/Sigma.cpp.s:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/Sigma.cpp.s
.PHONY : src/Sigma.cpp.s

src/sigma_ros_node.o: src/sigma_ros_node.cpp.o

.PHONY : src/sigma_ros_node.o

# target to build an object file
src/sigma_ros_node.cpp.o:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/sigma_ros_node.cpp.o
.PHONY : src/sigma_ros_node.cpp.o

src/sigma_ros_node.i: src/sigma_ros_node.cpp.i

.PHONY : src/sigma_ros_node.i

# target to preprocess a source file
src/sigma_ros_node.cpp.i:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/sigma_ros_node.cpp.i
.PHONY : src/sigma_ros_node.cpp.i

src/sigma_ros_node.s: src/sigma_ros_node.cpp.s

.PHONY : src/sigma_ros_node.s

# target to generate assembly for a file
src/sigma_ros_node.cpp.s:
	cd /home/bgusigma/amit_raven/src && $(MAKE) -f sigma_ros/CMakeFiles/sigma_ros_node.dir/build.make sigma_ros/CMakeFiles/sigma_ros_node.dir/src/sigma_ros_node.cpp.s
.PHONY : src/sigma_ros_node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... sigma_ros_genpy"
	@echo "... sigma_ros_gennodejs"
	@echo "... sigma_ros_generate_messages_cpp"
	@echo "... sigma_ros_geneus"
	@echo "... sigma_ros_generate_messages_py"
	@echo "... _sigma_ros_generate_messages_check_deps_haptic_commands"
	@echo "... edit_cache"
	@echo "... sigma_ros_generate_messages_eus"
	@echo "... sigma_ros_generate_messages"
	@echo "... _sigma_ros_generate_messages_check_deps_haptic_device"
	@echo "... sigma_ros_generate_messages_nodejs"
	@echo "... sigma_ros_gencpp"
	@echo "... sigma_ros_node"
	@echo "... sigma_ros_generate_messages_lisp"
	@echo "... sigma_ros_genlisp"
	@echo "... src/Sigma.o"
	@echo "... src/Sigma.i"
	@echo "... src/Sigma.s"
	@echo "... src/sigma_ros_node.o"
	@echo "... src/sigma_ros_node.i"
	@echo "... src/sigma_ros_node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/bgusigma/amit_raven/src && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

