set(_CATKIN_CURRENT_PACKAGE "sigma_ros")
set(sigma_ros_VERSION "0.0.0")
set(sigma_ros_MAINTAINER "bgusigma <bgusigma@todo.todo>")
set(sigma_ros_PACKAGE_FORMAT "2")
set(sigma_ros_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(sigma_ros_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(sigma_ros_BUILDTOOL_DEPENDS "catkin")
set(sigma_ros_BUILDTOOL_EXPORT_DEPENDS )
set(sigma_ros_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(sigma_ros_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(sigma_ros_TEST_DEPENDS )
set(sigma_ros_DOC_DEPENDS )
set(sigma_ros_DEPRECATED "")