// Generated by gencpp from file sigma_ros/haptic_device.msg
// DO NOT EDIT!


#ifndef SIGMA_ROS_MESSAGE_HAPTIC_DEVICE_H
#define SIGMA_ROS_MESSAGE_HAPTIC_DEVICE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sigma_ros
{
template <class ContainerAllocator>
struct haptic_device_
{
  typedef haptic_device_<ContainerAllocator> Type;

  haptic_device_()
    : position()
    , gripper()
    , orientation()  {
      position.assign(0.0);

      gripper.assign(0.0);

      orientation.assign(0.0);
  }
  haptic_device_(const ContainerAllocator& _alloc)
    : position()
    , gripper()
    , orientation()  {
  (void)_alloc;
      position.assign(0.0);

      gripper.assign(0.0);

      orientation.assign(0.0);
  }



   typedef boost::array<float, 6>  _position_type;
  _position_type position;

   typedef boost::array<float, 2>  _gripper_type;
  _gripper_type gripper;

   typedef boost::array<float, 18>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::sigma_ros::haptic_device_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sigma_ros::haptic_device_<ContainerAllocator> const> ConstPtr;

}; // struct haptic_device_

typedef ::sigma_ros::haptic_device_<std::allocator<void> > haptic_device;

typedef boost::shared_ptr< ::sigma_ros::haptic_device > haptic_devicePtr;
typedef boost::shared_ptr< ::sigma_ros::haptic_device const> haptic_deviceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sigma_ros::haptic_device_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sigma_ros::haptic_device_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sigma_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sigma_ros': ['/home/bgusigma/raven_ws/src/sigma_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sigma_ros::haptic_device_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sigma_ros::haptic_device_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sigma_ros::haptic_device_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sigma_ros::haptic_device_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sigma_ros::haptic_device_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sigma_ros::haptic_device_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sigma_ros::haptic_device_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b845e0f3b8c3459fc44ca6852aec2573";
  }

  static const char* value(const ::sigma_ros::haptic_device_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb845e0f3b8c3459fULL;
  static const uint64_t static_value2 = 0xc44ca6852aec2573ULL;
};

template<class ContainerAllocator>
struct DataType< ::sigma_ros::haptic_device_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sigma_ros/haptic_device";
  }

  static const char* value(const ::sigma_ros::haptic_device_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sigma_ros::haptic_device_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[6] position\n\
float32[2] gripper\n\
float32[18] orientation\n\
";
  }

  static const char* value(const ::sigma_ros::haptic_device_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sigma_ros::haptic_device_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.gripper);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct haptic_device_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sigma_ros::haptic_device_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sigma_ros::haptic_device_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "gripper[]" << std::endl;
    for (size_t i = 0; i < v.gripper.size(); ++i)
    {
      s << indent << "  gripper[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gripper[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIGMA_ROS_MESSAGE_HAPTIC_DEVICE_H
